export const USER_REPOSITORY = Symbol('USER_REPOSITORY');
export const CREATE_USER_SERVICE = Symbol('CREATE_USER_SERVICE');
export const LOGGER_HELPER = Symbol('LOGGER_HELPER');
export const UPDATE_USER_SERVICE = Symbol('UPDATE_USER_SERVICE');
export const LIST_USER_SERVICE = Symbol('LIST_USER_SERVICE');
export const DELETE_USER_SERVICE = Symbol('DELETE_USER_SERVICE');