version: '3.8'
services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    command: --init-file /data/application/init.sql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: '${MYSQL_PASSWORD}'
    ports:
      - '3306:3306'
    volumes:
      - ./init.sql:/data/application/init.sql
      - db:/var/lib/mysql
volumes:
  db:
    driver: local