export enum ErrorEnum {
  DATABASE_ERROR = 'DATABASE_ERROR',
  CANNOT_CONNECT = 'CANNOT_CONNECT_WITH_DATABASE',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  BAD_REQUEST = 'BAD_REQUEST',
  ENTITY_NOT_FOUND = 'ENTITY_NOT_FOUND',
}
